version: '3'
services:
        mongo:
                image: mongo
        opal:
                image: obiba/opal:snapshot
                #build: .
                ports:
                        - "9943:8443"
                        - "9980:8080"
                links:
                        - mongo
                        - rock1
                environment:
                        - OPAL_ADMINISTRATOR_PASSWORD=datashieldtest
                        - MONGO_HOST=mongo
                        - MONGO_PORT=27017
                        - ROCK_HOSTS=rock1:8085
                volumes:
                        - /tmp/demo-opal:/srv
        rock1:
                image: datashield/rock-base:latest
                environment:
                        - ROCK_ID=default-1
                        - ROCK_CLUSTER=default
                volumes:
                        - /tmp/demo-rserver:/srv