version: '3'
services:
        mongo:
                image: mongo
        opal:
                image: obiba/opal:latest
                ports:
                        - "9943:8443"
                        - "9980:8080"
                links:
                        - mongo
                        - rserver
                environment:
                        - OPAL_ADMINISTRATOR_PASSWORD=password
                        - MONGO_HOST=mongo
                        - MONGO_PORT=27017
                        - RSERVER_HOST=rserver
                volumes:
                        - /tmp/demo-opal:/srv
        rserver:
                image: obiba/opal-rserver:latest
                volumes:
                        - /tmp/demo-rserver:/srv
        mysqldata:
                image: mysql:5
                environment:
                        - MYSQL_DATABASE=opal
                        - MYSQL_ROOT_PASSWORD=password
                        - MYSQL_USER=opal
                        - MYSQL_PASSWORD=password

